### ISSUE TITLE
errors loading in tidy format data - wrong handling of blanks

### ISSUE THREAD

**Issue by BramVDBe** [NicWir/QurvE#11]
I wanted to use the QurvE package and load my growth data in a tidy format. Sadly, the read_data() command throws an error that is related with my blank cells (always at column 12). these blanks have only values, no replicate or concentration. Here, there are NAs but even when really forcing empty cells, the read_data() still fails. This is my minimal data file example:
[test.csv](https://github.com/NicWir/QurvE/files/13976626/test.csv)

`test<-read.csv("test.csv")

library(QurvE)

grodata_temp <- read_data(test,
                   csvsep = ';', # or ','
                   dec = '.', # or ','
                   sheet.growth = 1, # number (or "name") of the EXCEL file sheet containing data
                   subtract.blank = TRUE,
                   calib.growth = NULL)`

yields

> Sample data are stored in columns. If they are stored in row format, please run read_data() with data.format = 'row'.
Error in apply(df[(2:nrow(df))[!((2:nrow(df)) %in% blank.ndx)], 4:ncol(df)],  : 
  dim(X) must have a positive length

Longer data tables (with for example more timepoints or more blanks at different rows), also fails but with other errors:

> Error in `$<-.data.frame`(`*tmp*`, "Time", value = c(NA, NA, 0, 15, 30,  : 
  replacement has 84 rows, data has 658

As soon as I remove all the blank rows, no error is thrown. 
maybe @NicWir or @jpquast have an idea what is going on and can have a look at my solution(s).

**Comment by BramVDBe** [comment]
I looked at the tidy_to_custom and read_data functions and adjusted a few of these in my fork of the package: https://github.com/BramVDBe/QurvE_tidy/tree/master

Not sure whether the fork will be merged, I did make a pull request but there might be issues that I fail to see (or the developers might not be that active anymore).

**Comment by NicWir** [comment]
During the parsing of tidy data, if the combinations of Description/Concentration/Replicate were not unique (e.g., multiple 'Blank' samples without replicate number or Concentration values), a replicate number is now assigned automatically.

This is done with the following logic:

- If the "Replicate" value is NA, increasing numeric values are assigned as "Replicate"
- If the "Replicate" value is non-NA, increasing letters of the alphabet [A, B, C,...] are appended to the "Replicate" descriptors. 

The rationale behind this is that "Replicate" values are ignored for "Blank" samples and all blanks are combined into a single Blank value vector by calculating the averages across all time points. For non-Blank samples, replicates with the same numeric value followed by a letter (e.g., "1A", "1B") are combined by their average as well.

**Comment by BramVDBe** [comment]
Sorry to re-open this, but with the updated package, the exp design is converting characters/factors to numbers and the substract blank is not working. Your solution implementation is a bit different from my fork with the disappeared df[["Time"]] <- as.numeric(df[["Time"]]) in tidy_to_custom and the recoding of the replicate with increment_replicate and checking the similar ones. I can only assume characters/factors are converted to numbers somewhere in that process.

**Comment by NicWir** [comment]
Could you please provide a more detailed description of the new problem, ideally with an example file?

**Comment by BramVDBe** [comment]
ok this seems to be only related to the fact that description is a factor in my tidy table. 
[test.csv](https://github.com/NicWir/QurvE/files/14041291/test.csv)

`g2<-read.csv("test.csv")
g2$Description<-as.factor(g2$Description)
grodata_temp3 <- read_data(data.growth =g2,
                          csvsep = ';', # or ','
                          dec = '.', # or ','
                          sheet.growth = 1, # number (or "name") of the EXCEL file sheet containing data
                          subtract.blank = TRUE,
                          calib.growth = NULL)
`
==> looking in the grodata_temp3, I get numbers with my exp design for the description, also abolishing the blank names and therefore blanks cannot be corrected.

**Comment by NicWir** [comment]
I will add a step in which factors are converted to character. But, have you tried simply not converting your "Description" column to factors?

**Comment by BramVDBe** [comment]
Sure that is one solution :-). However, when working with tidy tibbles, I frequently need factors for plotting by factor or subsetting et al. Here, I only discovered that that was the only problem when making the test data file.

**Comment by NicWir** [comment]
Then dropping the factors inside the QurvE function should be an easy fix. Let me know if you encounter any other issues

**Comment by NicWir** [comment]
fix for factors in tidy dataframes/tibbles has been implemented
