### ISSUE TITLE
Reading fluorescence data from a biolector dataset

### ISSUE THREAD

**Issue by MTieke** [NicWir/QurvE#5]
Hello,
when I want to parse the data sheet of a biolector I can not assign fluorescence data from my data sheet. The program offers me to select between biomass gain 1, 3 and 5, even though I do not have gain 3 and 5 in my dataset. 

Could you help me with this issue? Thank you very much.

![Screenshot 2023-07-07 142357](https://github.com/NicWir/QurvE/assets/138880961/0fd1703b-33d4-4af8-8546-432f673abd77)

**Comment by NicWir** [comment]
The hallucination of non-existing channels is an interesting one. Are you willing to share your data file so that I can better troubleshoot what might be the issue with the incorrect parsing? Feel free to replace all sensitive or revealing information with dummy strings and measurement values with random numbers

**Comment by MTieke** [comment]
Hello,
Here is my file. I hope it will help. 
You will see that there are two sheets. One shows the raw data, and the other lacks biomass channels 3 and 5. 
Thank you.

[20230427-BiolectorData.xlsx](https://github.com/NicWir/QurvE/files/12012602/20230427-BiolectorData.xlsx)

**Comment by MTieke** [comment]
And here is the mapping of the data.
[Mapping.xlsx](https://github.com/NicWir/QurvE/files/12014685/Mapping.xlsx)

**Comment by NicWir** [comment]
Issue fixed. "GFP" was not recognized as a valid read type identifier for Biolector data. The parsing should work properly now when installing the QurvE R package with:
` devtools::install_github("NicWir/QurvE")`

The bugfix will be added to the web app very soon
