### ISSUE TITLE
QurvE | issue loading data

### ISSUE THREAD

**Issue by an-na-star** [NicWir/QurvE#6]
hi. every time i want to load my data into R with the provided code i get the error message "Error in `[.data.frame`(dat, , 3) : undefined columns selected". i have tried different approaches:
- data in custom format
- data in tidy format
- data in original format (with software Gen5)
- i don't have a "Concentration" factor but i have added the row (filled with 0s) because not having the row caused an error as well
my data files work perfectly fine in the application but i'd like to be able to work in R directly. i would be grateful for some elucidation on how to deal with this problem. overall, the package seems to be exactly what i was looking for.

**Comment by NicWir** [comment]
For data parsing issues, it would be very helpful to have the data files used to parse the data at hand. Since all three data formats (custom, tidy, original) failed, I suspect a conflict with naming conventions.

**Comment by an-na-star** [comment]
hi

thank you for the quick respnse. find attached a file of each type for one of my experimental plates (custom — P01new ; tidy — P01tidy ; original — P01raw). i appreciate your help.

best -
anna



On 13 Jul 2023, at 3:07 PM, Nicolas Wirth ***@***.***> wrote:



For data parsing issues, it would be very helpful to have the data files used to parse the data at hand. Since all three data formats (custom, tidy, original) failed, I suspect a conflict with naming conventions.

**Comment by NicWir** [comment]
I cannot see any file :-)

**Comment by an-na-star** [comment]
hi

thanks! i can try again but there were three files attached to the previous message.
***@***.***


best -
anna

Begin forwarded message:

**Comment by NicWir** [comment]
Please don't add the files as attachment in a reply email but upload them in a reply here:
https://github.com/NicWir/QurvE/issues/6

attachments get lost in the email conversations

**Comment by an-na-star** [comment]
thanks, i am sorry.

custom — P01new
tidy — P01tidy
original — P01raw


[P01new.csv](https://github.com/NicWir/QurvE/files/12041153/P01new.csv)
[P01tidy.csv](https://github.com/NicWir/QurvE/files/12041156/P01tidy.csv)
[P01raw.xlsx](https://github.com/NicWir/QurvE/files/12041163/P01raw.xlsx)

**Comment by NicWir** [comment]
I could not reproduce the error. The analysis completed without any errors for the data in custom format:

```
library(QurvE)

input <- read_data(data.growth = ".../P01new.csv",
                  csvsep = ",")

results <- QurvE::growth.workflow(input)
plot(results)
plot.parameter(results, param = "mu.spline")
```

I did, however, find a bug in the handling of tidy data. This should now also work correctly if you install the newest `QurvE`version from Github with:
```
devtools::install_github("NicWir/QurvE")
```

Then, you can read and analyze your tidy data like this:
```
library(QurvE)

data <- read_data(data.growth = ".../P01tidy.csv",
                  csvsep = ",")

results <- QurvE::growth.workflow(input)
plot(results)
plot.parameter(results, param = "mu.spline")
```

or, if you created the tidy dataframe within r as object `data_tidy`:
```
library(QurvE)

data <- read_data(data.growth = tidy_data)

results <- QurvE::growth.workflow(input)
plot(results)
plot.parameter(results, param = "mu.spline")
```

Thanks a lot for reporting this issue, making me notice the bugs in handling tidy data.

**Comment by BramVDBe** [comment]
I know this is a completed thread and I know I opened a similar issue but even with the latest QurvE, the tidy format is not working for me, also not for this mock example.
